### ISSUE TITLE
Could you use a LongAdder instead of AtomicLong

### ISSUE THREAD

**Issue by StevenCurran** [softwaremill/jox#14]
Usually better if you have a high amount of CAS contention. Seems you are updating these values in busy loops, so may be a better approach.

**Comment by adamw** [comment]
Thanks, I'll try this out!

**Comment by kaspernielsen** [comment]
A LongAdder is primarily used for calculating sums. It would not be applicable in your case.

**Comment by adamw** [comment]
Closing b/c of above
